### ISSUE TITLE
Getting an error when trying to create a PDF from Order page with the PDF Invoices & Packing Slips for WooCommerce plugin.

### ISSUE THREAD

**Issue by priyanka-tychesoftwares** [TycheSoftwares/woocommerce-delivery-notes#362]
**Describe the bug**
Getting an error when trying to create a PDF from Order page with the PDF Invoices & Packing Slips for WooCommerce plugin.

PHP Fatal error:  Uncaught TypeError: preg_match_all(): Argument #2 ($subject) must be of type string, array given in /home/velamaloro0065/web/priyanka-staging.instawp.xyz/public_html/wp-content/plugins/woocommerce-delivery-notes/includes/front/vendor/dompdf/dompdf/src/FrameReflower/AbstractFrameReflower.php:529
Stack trace:
#0 /home/velamaloro0065/web/priyanka-staging.instawp.xyz/public_html/wp-content/plugins/woocommerce-delivery-notes/includes/front/vendor/dompdf/dompdf/src/FrameReflower/AbstractFrameReflower.php(529): preg_match_all()
#1 /home/velamaloro0065/web/priyanka-staging.instawp.xyz/public_html/wp-content/plugins/woocommerce-delivery-notes/includes/front/vendor/dompdf/dompdf/src/FrameReflower/AbstractFrameReflower.php(557): Dompdf\FrameReflower\AbstractFrameReflower->_parse_quotes()
#2 /home/velamaloro0065/web/priyanka-staging.instawp.xyz/public_html/wp-content/plugins/woocommerce-delivery-notes/includes/front/vendor/dompdf/dompdf/src/FrameReflower/AbstractFrameReflower.php(687): Dompdf\FrameReflower\AbstractFrameReflower->_parse_content()
#3 /home/velamaloro0065/web/priyanka-staging.instawp.xyz/public_html/wp-content/plugins/woocommerce-delivery-notes/includes/front/vendor/dompdf/dompdf/src/FrameReflower/Block.php(796): Dompdf\FrameReflower\AbstractFrameReflower->_set_content()
#4 /home/velamaloro0065/web/priyanka-staging.instawp.xyz/public_html/wp-content/plugins/woocommerce-delivery-notes/includes/front/vendor/dompdf/dompdf/src/FrameDecorator/AbstractFrameDecorator.php(913): Dompdf\FrameReflower\Block->reflow()
#5 /home/velamaloro0065/web/priyanka-staging.instawp.xyz/public_html/wp-content/plugins/woocommerce-delivery-notes/includes/front/vendor/dompdf/dompdf/src/FrameReflower/Block.php(865): Dompdf\FrameDecorator\AbstractFrameDecorator->reflow()
#6 /home/velamaloro0065/web/priyanka-staging.instawp.xyz/public_html/wp-content/plugins/woocommerce-delivery-notes/includes/front/vendor/dompdf/dompdf/src/FrameDecorator/AbstractFrameDecorator.php(913): Dompdf\FrameReflower\Block->reflow()
#7 /home/velamaloro0065/web/priyanka-staging.instawp.xyz/public_html/wp-content/plugins/woocommerce-delivery-notes/includes/front/vendor/dompdf/dompdf/src/FrameReflower/Block.php(865): Dompdf\FrameDecorator\AbstractFrameDecorator->reflow()
#8 /home/velamaloro0065/web/priyanka-staging.instawp.xyz/public_html/wp-content/plugins/woocommerce-delivery-notes/includes/front/vendor/dompdf/dompdf/src/FrameDecorator/AbstractFrameDecorator.php(913): Dompdf\FrameReflower\Block->reflow()
#9 /home/velamaloro0065/web/priyanka-staging.instawp.xyz/public_html/wp-content/plugins/woocommerce-delivery-notes/includes/front/vendor/dompdf/dompdf/src/FrameReflower/Block.php(865): Dompdf\FrameDecorator\AbstractFrameDecorator->reflow()
#10 /home/velamaloro0065/web/priyanka-staging.instawp.xyz/public_html/wp-content/plugins/woocommerce-delivery-notes/includes/front/vendor/dompdf/dompdf/src/FrameDecorator/AbstractFrameDecorator.php(913): Dompdf\FrameReflower\Block->reflow()
#11 /home/velamaloro0065/web/priyanka-staging.instawp.xyz/public_html/wp-content/plugins/woocommerce-delivery-notes/includes/front/vendor/dompdf/dompdf/src/FrameReflower/Page.php(142): Dompdf\FrameDecorator\AbstractFrameDecorator->reflow()
#12 /home/velamaloro0065/web/priyanka-staging.instawp.xyz/public_html/wp-content/plugins/woocommerce-delivery-notes/includes/front/vendor/dompdf/dompdf/src/FrameDecorator/AbstractFrameDecorator.php(913): Dompdf\FrameReflower\Page->reflow()
#13 /home/velamaloro0065/web/priyanka-staging.instawp.xyz/public_html/wp-content/plugins/woocommerce-pdf-invoices-packing-slips/vendor/dompdf/dompdf/src/Dompdf.php(808): Dompdf\FrameDecorator\AbstractFrameDecorator->reflow()
#14 /home/velamaloro0065/web/priyanka-staging.instawp.xyz/public_html/wp-content/plugins/woocommerce-delivery-notes/includes/front/wcdn-front-function.php(51): Dompdf\Dompdf->render()
#15 /home/velamaloro0065/web/priyanka-staging.instawp.xyz/public_html/wp-content/plugins/woocommerce-delivery-notes/includes/class-wcdn-theme.php(69): create_pdf()
#16 /home/velamaloro0065/web/priyanka-staging.instawp.xyz/public_html/wp-includes/class-wp-hook.php(324): WCDN_Theme->attach_pdf_to_emails()
#17 /home/velamaloro0065/web/priyanka-staging.instawp.xyz/public_html/wp-includes/plugin.php(205): WP_Hook->apply_filters()
#18 /home/velamaloro0065/web/priyanka-staging.instawp.xyz/public_html/wp-content/plugins/woocommerce/includes/emails/class-wc-email.php(477): apply_filters()
#19 /home/velamaloro0065/web/priyanka-staging.instawp.xyz/public_html/wp-content/plugins/woocommerce/includes/emails/class-wc-email-new-order.php(112): WC_Email->get_attachments()
#20 /home/velamaloro0065/web/priyanka-staging.instawp.xyz/public_html/wp-includes/class-wp-hook.php(324): WC_Email_New_Order->trigger()
#21 /home/velamaloro0065/web/priyanka-staging.instawp.xyz/public_html/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters()
#22 /home/velamaloro0065/web/priyanka-staging.instawp.xyz/public_html/wp-includes/plugin.php(565): WP_Hook->do_action()
#23 /home/velamaloro0065/web/priyanka-staging.instawp.xyz/public_html/wp-content/plugins/woocommerce/includes/class-wc-emails.php(172): do_action_ref_array()
#24 /home/velamaloro0065/web/priyanka-staging.instawp.xyz/public_html/wp-includes/class-wp-hook.php(324): WC_Emails::send_transactional_email()
#25 /home/velamaloro0065/web/priyanka-staging.instawp.xyz/public_html/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters()
#26 /home/velamaloro0065/web/priyanka-staging.instawp.xyz/public_html/wp-includes/plugin.php(517): WP_Hook->do_action()
#27 /home/velamaloro0065/web/priyanka-staging.instawp.xyz/public_html/wp-content/plugins/woocommerce/includes/class-wc-order.php(420): do_action()
#28 /home/velamaloro0065/web/priyanka-staging.instawp.xyz/public_html/wp-content/plugins/woocommerce/includes/class-wc-order.php(253): WC_Order->status_transition()
#29 /home/velamaloro0065/web/priyanka-staging.instawp.xyz/public_html/wp-content/plugins/woocommerce/includes/class-wc-order.php(365): WC_Order->save()
#30 /home/velamaloro0065/web/priyanka-staging.instawp.xyz/public_html/wp-content/plugins/woocommerce/includes/gateways/bacs/class-wc-gateway-bacs.php(390): WC_Order->update_status()
#31 /home/velamaloro0065/web/priyanka-staging.instawp.xyz/public_html/wp-content/plugins/woocommerce/includes/class-wc-checkout.php(1062): WC_Gateway_BACS->process_payment()
#32 /home/velamaloro0065/web/priyanka-staging.instawp.xyz/public_html/wp-content/plugins/woocommerce/includes/class-wc-checkout.php(1293): WC_Checkout->process_order_payment()
#33 /home/velamaloro0065/web/priyanka-staging.instawp.xyz/public_html/wp-content/plugins/woocommerce/includes/class-wc-ajax.php(520): WC_Checkout->process_checkout()
#34 /home/velamaloro0065/web/priyanka-staging.instawp.xyz/public_html/wp-includes/class-wp-hook.php(324): WC_AJAX::checkout()
#35 /home/velamaloro0065/web/priyanka-staging.instawp.xyz/public_html/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters()
#36 /home/velamaloro0065/web/priyanka-staging.instawp.xyz/public_html/wp-includes/plugin.php(517): WP_Hook->do_action()
#37 /home/velamaloro0065/web/priyanka-staging.instawp.xyz/public_html/wp-content/plugins/woocommerce/includes/class-wc-ajax.php(96): do_action()
#38 /home/velamaloro0065/web/priyanka-staging.instawp.xyz/public_html/wp-includes/class-wp-hook.php(324): WC_AJAX::do_wc_ajax()
#39 /home/velamaloro0065/web/priyanka-staging.instawp.xyz/public_html/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters()
#40 /home/velamaloro0065/web/priyanka-staging.instawp.xyz/public_html/wp-includes/plugin.php(517): WP_Hook->do_action()
#41 /home/velamaloro0065/web/priyanka-staging.instawp.xyz/public_html/wp-includes/template-loader.php(13): do_action()
#42 /home/velamaloro0065/web/priyanka-staging.instawp.xyz/public_html/wp-blog-header.php(19): require_once('...')
#43 /home/velamaloro0065/web/priyanka-staging.instawp.xyz/public_html/index.php(17): require('...')
#44 {main}
  thrown in /home/velamaloro0065/web/priyanka-staging.instawp.xyz/public_html/wp-content/plugins/woocommerce-delivery-notes/includes/front/vendor/dompdf/dompdf/src/FrameReflower/AbstractFrameReflower.php on line 529
  
**To Reproduce**
1. Install and activate the "PDF Invoices & Packing Slips for WooCommerce" plugin with our Print Invoice plugin.
2. Set up the plugin settings. 
3. Go to the WC Orders page and click on the "Print Invoice" button for any orders. Also, try to place an order for the product.
4. You will not be able to place an order and this above error got logged in the debug log file.

**Expected behavior**
Such an error should not occur in the debug log when using our plugin with the PDF Invoices & Packing Slips for WooCommerce plugin.

**Screenshots or Video**

**Isolating the problem (mark completed items with an [x]):**
- [x] This bug happens with only WooCommerce Print Invoice & Delivery Note plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront]
- [x] I can reproduce this bug consistently using the steps above

**Additional context**
https://wordpress.org/support/topic/error-when-trying-to-get-a-pdf/

**Comment by priyanka-tychesoftwares** [comment]
Another client reported this error: https://support.tychesoftwares.com/conversation/2587?folder_id=15
